### ISSUE TITLE
About baseline.py and .conv

### ISSUE THREAD

**Issue by XiaobinHong** [ZhuYun97/ENGINE#2]
In the README, CUDA_VISIBLE_DEVICES=5 python baselines.py --config ./configs/cora/gnn.yaml
but there is no file named baseline.py.

And, in models/encoder.py line 10, 
from .conv import *
ModuleNotFoundError: No module named 'models.conv'

How to debug for that?

**Comment by ZhuYun97** [comment]
Thank you for your feedback. Please use `traditional_gnn.py` instead of `baseline.py`. The `README.md` has been updated accordingly. Regarding the second bug, annotating `from .conv import *` should resolve the issue.
