### ISSUE TITLE
Question about datasets

### ISSUE THREAD

**Issue by 1957787636** [ZhuYun97/ENGINE#3]
Hi, I do not find the file on Photo and Wikics datasets in preprocessed_data, could you provide further data?

**Comment by ZhuYun97** [comment]
Hi, you can access these datasets from this [link](https://drive.google.com/drive/folders/1bSRCZxt0c11A3717DYDjO112fo_zC8Ec). Thanks for your feedback, the `README.md` has been updated accordingly.

**Comment by 1957787636** [comment]
Hi, a further question, the Google drive do not have text file.
FileNotFoundError: [Errno 2] No such file or directory: './datasets/TAG_Benchmark/Photo/Electronics-Photo.txt'

**Comment by ZhuYun97** [comment]
Thank you for the additional feedback. We have now packed the raw texts into `photo.pt`. You can download it from the following [link](https://drive.google.com/drive/folders/1bSRCZxt0c11A3717DYDjO112fo_zC8Ec). Additionally, the code in `load_photo.py` has been updated to reflect these changes.
