### ISSUE TITLE
question about the accuracy of baselines

### ISSUE THREAD

**Issue by initzhang** [ZhuYun97/ENGINE#4]
Hi team, thanks for this interesting work!

I am confused about the accuracy of the baselines reported in the paper. For example, as reported in the Table 1 of [SimTeG paper](https://arxiv.org/abs/2308.02565) it achieves ~76.8% acc on Ogbn-Arxiv and ~84.6% acc on Ogbn-Products with the SAGE backbone. However, in the Table 2 of the ENGINE paper, the reported acc is much lower (~75.3% and ~74.5%). The situation is similar for GLEM etc. Could you explain what causes such difference? Thank you!

**Comment by ZhuYun97** [comment]
Thanks for your question. The discrepancies primarily arise from variations in model configuration and dataset size. For simplicity, we maintain consistency across all methods by using the same hidden size for the GNN, as documented in Table 10. Additionally, for the OGBN-Products dataset, we use a subset following [TAPE](https://github.com/XiaoxinHe/TAPE), as outlined in Table 1, which results in divergent performance outcomes.

**Comment by initzhang** [comment]
Hi @ZhuYun97 , thanks for the explanation!
For TAPE, the utilised LLM API is expensive which makes it less practical to do a full validation/test. However, for ENGINE, the efficiency and scalability is greatly boosted and a full validation/test should be viable. In addition, the GNNs in Table 10 seem to have small hidden size and shallow depth. Do you have any future plans of testing ENGINE with larger GNNs, such as a [default 3-layer GraphSAGE with hidden=256](https://github.com/snap-stanford/ogb/tree/master/examples/nodeproppred/arxiv) in OGB example?

**Comment by ZhuYun97** [comment]
Thanks for your further concerns. We plan to conduct larger-scale experiments in future iterations.

**Comment by initzhang** [comment]
Got it, thanks for your reply! I have no further questions.
